### ISSUE TITLE
[TwitterSummarization.py]-TypeError

### ISSUE THREAD

**Issue by qinjinjia** [abbottn3/EC500#2]
Meet a new problem on your code, any solution? Thanks.
```
Traceback (most recent call last):
  File "TwitterSummarization.py", line 209, in <module>
    main()
  File "TwitterSummarization.py", line 201, in main
    description_dict = gVision_and_FFMPEG(pic_urls)
  File "TwitterSummarization.py", line 143, in gVision_and_FFMPEG
    if webnotes.web_entities[0] > escore:
TypeError: '>' not supported between instances of 'WebEntity' and 'int'
```

**Comment by abbottn3** [comment]
Are you on a Mac or PC?

**Comment by qinjinjia** [comment]
On a Mac.

**Comment by abbottn3** [comment]
Okay well I am able to index with ints on my machine, and I've heard people
are having compatibility issues, so that might be why. You can try
accessing the first element in a different way (like with a for loop or
something). Additionally, Osama said that if people are having too much
trouble making the programs work cross platform, you can just do the test
cases for your own program and only do the text peer review on mine.

**Comment by qinjinjia** [comment]
ok, thank you very much.
